/* eslint-disable */
const dummyData = [
  {
    id: 1,
    username: 'kimk',
    votes: 1,
    answers: 0,
    views: 2,
    awards: 3012,
    title: 'Calculate value in textbox',
    content: 'I have 6 textboxes. How to calculate the total of value entered by users. Users need to enter quantity in each textbox and then it willcalculate with price that already display or show in label (quantity*price). The result will be showed in textbox readonly. Is it I need to use JavaScript? Can it be done by that?',
  },
  {
    id: 2,
    username: 'Rana sharjeel Ali',
    votes: 2,
    answers: 0,
    views: 3,
    awards: 12,
    title: 'I am creating a flutter app to detect hand gestures and convert them in Text for deaf and dumb people',
    content: 'Is there anybody who can provide me a road map on how to start the project, from where I can get the data set, and how to convert hand gestures to text? or is there any SDK or API, it will be great if you can provide me git link',
  },
  {
    id: 3,
    username: 'Naveen',
    votes: 3,
    answers: 0,
    views: 4,
    awards: 52,
    title: 'NodejS: memory usage of worker threads',
    content: 'Is there a way to obtain heap usage statistics of each worker threads in nodejs? Im looking for something similar to getHeapStatistics() of v8 module. Mostly ill just be needing the values of used heap size and max heap limit.',
  },
  {
    id: 4,
    username: 'Michael Sembach',
    votes: 4,
    answers: 0,
    views: 7,
    awards: 662,
    title: 'My chromebook has an inner HTML javascript connectivity error, how can I fix it?',
    content: 'When trying to connect to my ScrabbleGo app I keep getting an inner HTML internet connectivity javascript error, My internet connection shows a strong connection. I dont understand why it wont or cant connect my scrabbleGo game . All my other apps connect ok, but this one decided to have a connection error. How do I fix it ? Do I need to delete/remove the app then download the app/game again ?',
  },
  {
    id: 5,
    username: 'saba mushtaq',
    votes: 5,
    answers: 0,
    views: 20,
    awards: 833,
    title: 'Form validation in Reactjs onchange input fields',
    content: 'Hello I am new learner of react. anybody please help me in form validation on(onchange) input Fields',
  },
  {
    id: 6,
    username: 'Gowry Kanth',
    votes: 6,
    answers: 0,
    views: 4,
    awards: 12,
    title: 'Return value must be of type Laravel 10',
    content: 'i am creating the laravel 10 project.i want to view records controller to view i ran into the problem with this.',
  },
  {
    id: 7,
    username: 'foxywaxy',
    votes: 7,
    answers: 0,
    views: 6,
    awards: 10,
    title: 'How to display dynamic data in a modal',
    content: 'I want data fetched from database To display dynamic data in the modal based on the rows id, here is what I have done. the modal only displays data of the first row in the database. i want the modal to dynamically show data based on the row ids in the database. what am i doing wrong or what do i need to change or add. thank you',
  },
  {
    id: 8,
    username: 'Ashu',
    votes: 8,
    answers: 0,
    views: 3,
    awards: 2,
    title: 'Correct way of Calling Reference Cursors in Postgres 11 and above using JDBC Driver',
    content: 'Hello Experts, I need some suggestion on how to get the data through Postgres JDBC Driver from Stored Procedures having Reference Cursors.',
  },
  {
    id: 9,
    username: 'anuj',
    votes: 9,
    answers: 0,
    views: 5,
    awards: 98,
    title: 'How do I change the position of the label in the Nodes of ReactFlow?',
    content: 'I am trying to change the position of the label of reactflow node from Center to the left side and rotate it 90deg, for example something like this.',
  },
  {
    id: 10,
    username: 'Gowry Kanth',
    votes: 10,
    answers: 0,
    views: 4,
    awards: 665,
    title: 'Return value must be of type Laravel 10',
    content: 'i am creating the laravel 10 project.i want to view records controller to view i ran into the problem with this.',
  },
  {
    id: 11,
    username: 'Christine',
    votes: 11,
    answers: 0,
    views: 3,
    awards: 30,
    title: 'Ramda recursive curried function throws Maximum call stack size exceeded',
    content: 'I try to understand ramda a bit better and why in the following example mapTreeNode2 does not work exactly like mapTreeNode.',
  },
  {
    id: 12,
    username: 'Sake',
    votes: 12,
    answers: 0,
    views: 3,
    awards: 853,
    title: 'do we have any alternative solution for WHERE VALUE IS NOT NULL MySQL Query?',
    content: 'I have tried above query, it is taking more time to check where condition (1.5 seconds). do we have any alternative solution for above query. it help me a lot. because in my case I need to query multiple rows to filter not null values.',
  },
  {
    id: 13,
    username: 'ymmx',
    votes: 13,
    answers: 0,
    views: 5,
    awards: 1560,
    title: 'How make tensorflow use GPU?',
    content: 'Im working with python and I would like to use tensorflow with my GTX2080TI but tensorflow is using only the CPU.',
  },
  {
    id: 14,
    username: 'Jazyzz',
    votes: 14,
    answers: 0,
    views: 5,
    awards: 1,
    title: 'Table rows delete function not working - PostgreSQL, PHP, AJAX',
    content: 'Im using PHP and Ajax to bind my data to the HTML table. Now I added a button that deletes table rows by id but it doesnt work as expected. I get a message from var conf = confirm() but nothing happens after that.',
  },
  {
    id: 15,
    username: 'BetterPro',
    votes: 15,
    answers: 0,
    views: 3,
    awards: 4660,
    title: 'crash App iOS flutter when I use shazamkit package',
    content: 'I am using shazamkit package to recognize sound in flutter. android version works perfect but in iOS version when I start to use get this error:',
  },
  {
    id: 16,
    username: 'kimk',
    votes: 16,
    answers: 0,
    views: 2,
    awards: 3012,
    title: 'Calculate value in textbox',
    content: 'I have 6 textboxes. How to calculate the total of value entered by users. Users need to enter quantity in each textbox and then it willcalculate with price that already display or show in label (quantity*price). The result will be showed in textbox readonly. Is it I need to use JavaScript? Can it be done by that?',
  },
  {
    id: 17,
    username: 'Rana sharjeel Ali',
    votes: 17,
    answers: 0,
    views: 3,
    awards: 12,
    title: 'I am creating a flutter app to detect hand gestures and convert them in Text for deaf and dumb people',
    content: 'Is there anybody who can provide me a road map on how to start the project, from where I can get the data set, and how to convert hand gestures to text? or is there any SDK or API, it will be great if you can provide me git link',
  },
  {
    id: 18,
    username: 'Naveen',
    votes: 18,
    answers: 0,
    views: 4,
    awards: 52,
    title: 'NodejS: memory usage of worker threads',
    content: 'Is there a way to obtain heap usage statistics of each worker threads in nodejs? Im looking for something similar to getHeapStatistics() of v8 module. Mostly ill just be needing the values of used heap size and max heap limit.',
  },
  {
    id: 19,
    username: 'Michael Sembach',
    votes: 19,
    answers: 0,
    views: 7,
    awards: 662,
    title: 'My chromebook has an inner HTML javascript connectivity error, how can I fix it?',
    content: 'When trying to connect to my ScrabbleGo app I keep getting an inner HTML internet connectivity javascript error, My internet connection shows a strong connection. I dont understand why it wont or cant connect my scrabbleGo game . All my other apps connect ok, but this one decided to have a connection error. How do I fix it ? Do I need to delete/remove the app then download the app/game again ?',
  },
  {
    id: 20,
    username: 'saba mushtaq',
    votes: 20,
    answers: 0,
    views: 20,
    awards: 833,
    title: 'Form validation in Reactjs onchange input fields',
    content: 'Hello I am new learner of react. anybody please help me in form validation on(onchange) input Fields',
  },
  {
    id: 21,
    username: 'Gowry Kanth',
    votes: 21,
    answers: 0,
    views: 4,
    awards: 12,
    title: 'Return value must be of type Laravel 10',
    content: 'i am creating the laravel 10 project.i want to view records controller to view i ran into the problem with this.',
  },
  {
    id: 22,
    username: 'foxywaxy',
    votes: 22,
    answers: 0,
    views: 6,
    awards: 10,
    title: 'How to display dynamic data in a modal',
    content: 'I want data fetched from database To display dynamic data in the modal based on the rows id, here is what I have done. the modal only displays data of the first row in the database. i want the modal to dynamically show data based on the row ids in the database. what am i doing wrong or what do i need to change or add. thank you',
  },
  {
    id: 23,
    username: 'Ashu',
    votes: 23,
    answers: 0,
    views: 3,
    awards: 2,
    title: 'Correct way of Calling Reference Cursors in Postgres 11 and above using JDBC Driver',
    content: 'Hello Experts, I need some suggestion on how to get the data through Postgres JDBC Driver from Stored Procedures having Reference Cursors.',
  },
  {
    id: 24,
    username: 'anuj',
    votes: 24,
    answers: 0,
    views: 5,
    awards: 98,
    title: 'How do I change the position of the label in the Nodes of ReactFlow?',
    content: 'I am trying to change the position of the label of reactflow node from Center to the left side and rotate it 90deg, for example something like this.',
  },
  {
    id: 25,
    username: 'Gowry Kanth',
    votes: 25,
    answers: 0,
    views: 4,
    awards: 665,
    title: 'Return value must be of type Laravel 10',
    content: 'i am creating the laravel 10 project.i want to view records controller to view i ran into the problem with this.',
  },
  {
    id: 26,
    username: 'Christine',
    votes: 26,
    answers: 0,
    views: 3,
    awards: 30,
    title: 'Ramda recursive curried function throws Maximum call stack size exceeded',
    content: 'I try to understand ramda a bit better and why in the following example mapTreeNode2 does not work exactly like mapTreeNode.',
  },
  {
    id: 27,
    username: 'Sake',
    votes: 27,
    answers: 0,
    views: 3,
    awards: 853,
    title: 'do we have any alternative solution for WHERE VALUE IS NOT NULL MySQL Query?',
    content: 'I have tried above query, it is taking more time to check where condition (1.5 seconds). do we have any alternative solution for above query. it help me a lot. because in my case I need to query multiple rows to filter not null values.',
  },
  {
    id: 28,
    username: 'ymmx',
    votes: 28,
    answers: 0,
    views: 5,
    awards: 1560,
    title: 'How make tensorflow use GPU?',
    content: 'Im working with python and I would like to use tensorflow with my GTX2080TI but tensorflow is using only the CPU.',
  },
  {
    id: 29,
    username: 'Jazyzz',
    votes: 29,
    answers: 0,
    views: 5,
    awards: 1,
    title: 'Table rows delete function not working - PostgreSQL, PHP, AJAX',
    content: 'Im using PHP and Ajax to bind my data to the HTML table. Now I added a button that deletes table rows by id but it doesnt work as expected. I get a message from var conf = confirm() but nothing happens after that.',
  },
  {
    id: 30,
    username: 'BetterPro',
    votes: 30,
    answers: 0,
    views: 3,
    awards: 4660,
    title: 'crash App iOS flutter when I use shazamkit package',
    content: 'I am using shazamkit package to recognize sound in flutter. android version works perfect but in iOS version when I start to use get this error:',
  },
  {
    id: 31,
    username: 'kimk',
    votes: 31,
    answers: 0,
    views: 2,
    awards: 3012,
    title: 'Calculate value in textbox',
    content: 'I have 6 textboxes. How to calculate the total of value entered by users. Users need to enter quantity in each textbox and then it willcalculate with price that already display or show in label (quantity*price). The result will be showed in textbox readonly. Is it I need to use JavaScript? Can it be done by that?',
  },
  {
    id: 32,
    username: 'Rana sharjeel Ali',
    votes: 32,
    answers: 0,
    views: 3,
    awards: 12,
    title: 'I am creating a flutter app to detect hand gestures and convert them in Text for deaf and dumb people',
    content: 'Is there anybody who can provide me a road map on how to start the project, from where I can get the data set, and how to convert hand gestures to text? or is there any SDK or API, it will be great if you can provide me git link',
  },
  {
    id: 33,
    username: 'Naveen',
    votes: 33,
    answers: 0,
    views: 4,
    awards: 52,
    title: 'NodejS: memory usage of worker threads',
    content: 'Is there a way to obtain heap usage statistics of each worker threads in nodejs? Im looking for something similar to getHeapStatistics() of v8 module. Mostly ill just be needing the values of used heap size and max heap limit.',
  },
  {
    id: 34,
    username: 'Michael Sembach',
    votes: 34,
    answers: 0,
    views: 7,
    awards: 662,
    title: 'My chromebook has an inner HTML javascript connectivity error, how can I fix it?',
    content: 'When trying to connect to my ScrabbleGo app I keep getting an inner HTML internet connectivity javascript error, My internet connection shows a strong connection. I dont understand why it wont or cant connect my scrabbleGo game . All my other apps connect ok, but this one decided to have a connection error. How do I fix it ? Do I need to delete/remove the app then download the app/game again ?',
  },
  {
    id: 35,
    username: 'saba mushtaq',
    votes: 35,
    answers: 0,
    views: 20,
    awards: 833,
    title: 'Form validation in Reactjs onchange input fields',
    content: 'Hello I am new learner of react. anybody please help me in form validation on(onchange) input Fields',
  },
  {
    id: 36,
    username: 'Gowry Kanth',
    votes: 36,
    answers: 0,
    views: 4,
    awards: 12,
    title: 'Return value must be of type Laravel 10',
    content: 'i am creating the laravel 10 project.i want to view records controller to view i ran into the problem with this.',
  },
  {
    id: 37,
    username: 'foxywaxy',
    votes: 37,
    answers: 0,
    views: 6,
    awards: 10,
    title: 'How to display dynamic data in a modal',
    content: 'I want data fetched from database To display dynamic data in the modal based on the rows id, here is what I have done. the modal only displays data of the first row in the database. i want the modal to dynamically show data based on the row ids in the database. what am i doing wrong or what do i need to change or add. thank you',
  },
  {
    id: 38,
    username: 'Ashu',
    votes: 38,
    answers: 0,
    views: 3,
    awards: 2,
    title: 'Correct way of Calling Reference Cursors in Postgres 11 and above using JDBC Driver',
    content: 'Hello Experts, I need some suggestion on how to get the data through Postgres JDBC Driver from Stored Procedures having Reference Cursors.',
  },
  {
    id: 39,
    username: 'anuj',
    votes: 39,
    answers: 0,
    views: 5,
    awards: 98,
    title: 'How do I change the position of the label in the Nodes of ReactFlow?',
    content: 'I am trying to change the position of the label of reactflow node from Center to the left side and rotate it 90deg, for example something like this.',
  },
  {
    id: 40,
    username: 'Gowry Kanth',
    votes: 40,
    answers: 0,
    views: 4,
    awards: 665,
    title: 'Return value must be of type Laravel 10',
    content: 'i am creating the laravel 10 project.i want to view records controller to view i ran into the problem with this.',
  },
  {
    id: 41,
    username: 'Christine',
    votes: 41,
    answers: 0,
    views: 3,
    awards: 30,
    title: 'Ramda recursive curried function throws Maximum call stack size exceeded',
    content: 'I try to understand ramda a bit better and why in the following example mapTreeNode2 does not work exactly like mapTreeNode.',
  },
  {
    id: 42,
    username: 'Sake',
    votes: 42,
    answers: 0,
    views: 3,
    awards: 853,
    title: 'do we have any alternative solution for WHERE VALUE IS NOT NULL MySQL Query?',
    content: 'I have tried above query, it is taking more time to check where condition (1.5 seconds). do we have any alternative solution for above query. it help me a lot. because in my case I need to query multiple rows to filter not null values.',
  },
  {
    id: 43,
    username: 'ymmx',
    votes: 43,
    answers: 0,
    views: 5,
    awards: 1560,
    title: 'How make tensorflow use GPU?',
    content: 'Im working with python and I would like to use tensorflow with my GTX2080TI but tensorflow is using only the CPU.',
  },
  {
    id: 44,
    username: 'Jazyzz',
    votes: 44,
    answers: 0,
    views: 5,
    awards: 1,
    title: 'Table rows delete function not working - PostgreSQL, PHP, AJAX',
    content: 'Im using PHP and Ajax to bind my data to the HTML table. Now I added a button that deletes table rows by id but it doesnt work as expected. I get a message from var conf = confirm() but nothing happens after that.',
  },
  {
    id: 45,
    username: 'BetterPro',
    votes: 45,
    answers: 0,
    views: 3,
    awards: 4660,
    title: 'crash App iOS flutter when I use shazamkit package',
    content: 'I am using shazamkit package to recognize sound in flutter. android version works perfect but in iOS version when I start to use get this error:',
  },
  {
    id: 46,
    username: 'kimk',
    votes: 46,
    answers: 0,
    views: 2,
    awards: 3012,
    title: 'Calculate value in textbox',
    content: 'I have 6 textboxes. How to calculate the total of value entered by users. Users need to enter quantity in each textbox and then it willcalculate with price that already display or show in label (quantity*price). The result will be showed in textbox readonly. Is it I need to use JavaScript? Can it be done by that?',
  },
  {
    id: 47,
    username: 'Rana sharjeel Ali',
    votes: 47,
    answers: 0,
    views: 3,
    awards: 12,
    title: 'I am creating a flutter app to detect hand gestures and convert them in Text for deaf and dumb people',
    content: 'Is there anybody who can provide me a road map on how to start the project, from where I can get the data set, and how to convert hand gestures to text? or is there any SDK or API, it will be great if you can provide me git link',
  },
  {
    id: 48,
    username: 'Naveen',
    votes: 48,
    answers: 0,
    views: 4,
    awards: 52,
    title: 'NodejS: memory usage of worker threads',
    content: 'Is there a way to obtain heap usage statistics of each worker threads in nodejs? Im looking for something similar to getHeapStatistics() of v8 module. Mostly ill just be needing the values of used heap size and max heap limit.',
  },
  {
    id: 49,
    username: 'Michael Sembach',
    votes: 49,
    answers: 0,
    views: 7,
    awards: 662,
    title: 'My chromebook has an inner HTML javascript connectivity error, how can I fix it?',
    content: 'When trying to connect to my ScrabbleGo app I keep getting an inner HTML internet connectivity javascript error, My internet connection shows a strong connection. I dont understand why it wont or cant connect my scrabbleGo game . All my other apps connect ok, but this one decided to have a connection error. How do I fix it ? Do I need to delete/remove the app then download the app/game again ?',
  },
  {
    id: 50,
    username: 'saba mushtaq',
    votes: 50,
    answers: 0,
    views: 20,
    awards: 833,
    title: 'Form validation in Reactjs onchange input fields',
    content: 'Hello I am new learner of react. anybody please help me in form validation on(onchange) input Fields',
  },
  {
    id: 51,
    username: 'Gowry Kanth',
    votes: 51,
    answers: 0,
    views: 4,
    awards: 12,
    title: 'Return value must be of type Laravel 10',
    content: 'i am creating the laravel 10 project.i want to view records controller to view i ran into the problem with this.',
  },
  {
    id: 52,
    username: 'foxywaxy',
    votes: 52,
    answers: 0,
    views: 6,
    awards: 10,
    title: 'How to display dynamic data in a modal',
    content: 'I want data fetched from database To display dynamic data in the modal based on the rows id, here is what I have done. the modal only displays data of the first row in the database. i want the modal to dynamically show data based on the row ids in the database. what am i doing wrong or what do i need to change or add. thank you',
  },
  {
    id: 53,
    username: 'Ashu',
    votes: 53,
    answers: 0,
    views: 3,
    awards: 2,
    title: 'Correct way of Calling Reference Cursors in Postgres 11 and above using JDBC Driver',
    content: 'Hello Experts, I need some suggestion on how to get the data through Postgres JDBC Driver from Stored Procedures having Reference Cursors.',
  },
  {
    id: 54,
    username: 'anuj',
    votes: 54,
    answers: 0,
    views: 5,
    awards: 98,
    title: 'How do I change the position of the label in the Nodes of ReactFlow?',
    content: 'I am trying to change the position of the label of reactflow node from Center to the left side and rotate it 90deg, for example something like this.',
  },
  {
    id: 55,
    username: 'Gowry Kanth',
    votes: 55,
    answers: 0,
    views: 4,
    awards: 665,
    title: 'Return value must be of type Laravel 10',
    content: 'i am creating the laravel 10 project.i want to view records controller to view i ran into the problem with this.',
  },
  {
    id: 56,
    username: 'Christine',
    votes: 56,
    answers: 0,
    views: 3,
    awards: 30,
    title: 'Ramda recursive curried function throws Maximum call stack size exceeded',
    content: 'I try to understand ramda a bit better and why in the following example mapTreeNode2 does not work exactly like mapTreeNode.',
  },
  {
    id: 57,
    username: 'Sake',
    votes: 57,
    answers: 0,
    views: 3,
    awards: 853,
    title: 'do we have any alternative solution for WHERE VALUE IS NOT NULL MySQL Query?',
    content: 'I have tried above query, it is taking more time to check where condition (1.5 seconds). do we have any alternative solution for above query. it help me a lot. because in my case I need to query multiple rows to filter not null values.',
  },
  {
    id: 58,
    username: 'ymmx',
    votes: 58,
    answers: 0,
    views: 5,
    awards: 1560,
    title: 'How make tensorflow use GPU?',
    content: 'Im working with python and I would like to use tensorflow with my GTX2080TI but tensorflow is using only the CPU.',
  },
  {
    id: 59,
    username: 'Jazyzz',
    votes: 59,
    answers: 0,
    views: 5,
    awards: 1,
    title: 'Table rows delete function not working - PostgreSQL, PHP, AJAX',
    content: 'Im using PHP and Ajax to bind my data to the HTML table. Now I added a button that deletes table rows by id but it doesnt work as expected. I get a message from var conf = confirm() but nothing happens after that.',
  },
  {
    id: 60,
    username: 'BetterPro',
    votes: 60,
    answers: 0,
    views: 3,
    awards: 4660,
    title: 'crash App iOS flutter when I use shazamkit package',
    content: 'I am using shazamkit package to recognize sound in flutter. android version works perfect but in iOS version when I start to use get this error:',
  },
];

export default dummyData;
